#
# (C) Copyright 2000, 2001, 2002
# Wolfgang Denk, DENX Software Engineering, wd@denx.de.
#
# SPDX-License-Identifier:	GPL-2.0+
#

ifdef CONFIG_SPL_BUILD
obj-y	:= spl.o common.o bootsplash.o
else
obj-y	:= var_som.o common.o bootsplash.o
endif
